### ISSUE TITLE
failure on new installs and when using clear

### ISSUE THREAD

**Issue by bootstrap-prime** [badjr13/laydown#19]
file clearing and initialization does not populate the new file with an empty struct, causing deserialization failure.

**Comment by badjr13** [comment]
Can you post the steps to reproduce? I've been using `clear` on a daily basis without issue. I may be misunderstanding the problem you're having.

**Comment by badjr13** [comment]
@bootstrap-prime and @klara-meyer 

This issue has been fixed and published. You can update `laydown` by running `cargo install laydown` to pull down version `1.4.1`.

Sorry for the odd workflow. This is my first open-source project. I probably should have turned this into a Pull Request and haven't gotten around to learning how to do proper releases on GitHub yet.

Thank you for opening this issue.
