### ISSUE TITLE
Feature request: use the $EDITOR variable to select a text editor

### ISSUE THREAD

**Issue by Lucretiel** [badjr13/laydown#2]
It's a common convention in many CLI tools to use the `$EDITOR` environment variable as a path to the user's preferred text editor. Notable examples include `git` and `sudoedit`. It's be a fairly straightforward change:

```rust
let default_editor = std::env::var("EDITOR").as_deref().unwrap_or("vi");
```

**Comment by badjr13** [comment]
This feature has been added and can be seen in this [commit](https://github.com/badjr13/laydown/commit/5b8c4a82a2362e0ed6a902e8166bb570f6dab403). Thank you for the request!
