### ISSUE TITLE
Semver break: there is no auto-migration from 1.1.0 -> 1.5.0

### ISSUE THREAD

**Issue by Zykino** [badjr13/laydown#22]
```sh
laydown
thread 'main' panicked at 'Failed to deserialize content from laydown.ron: missing field `history`', /home/x667421/.cargo/registry/src/github.com-1ecc6299db9ec823/laydown-1.5.0/src/data_file.rs:52:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Rust crates usually try to follow https://semver.org/ meaning that no break should happen if there is not a new major version.
`history` field could be optional (only when reading?) and you won't need to tag a version 2.0 this way.

**Comment by badjr13** [comment]
Thank you for creating this issue. I will look into fixing this when I have an opportunity.

**Comment by badjr13** [comment]
This was fixed as part of this PR - https://github.com/badjr13/laydown/pull/26
