### ISSUE TITLE
Deserialize `laydown.ron` only when necessary

### ISSUE THREAD

**Issue by Zykino** [badjr13/laydown#23]
```sh
laydown --help
thread 'main' panicked at 'Failed to deserialize content from laydown.ron: missing field `history`', /home/x667421/.cargo/registry/src/github.com-1ecc6299db9ec823/laydown-1.5.0/src/data_file.rs:52:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

laydown --version
thread 'main' panicked at 'Failed to deserialize content from laydown.ron: missing field `history`', /home/x667421/.cargo/registry/src/github.com-1ecc6299db9ec823/laydown-1.5.0/src/data_file.rs:52:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

laydown edit
thread 'main' panicked at 'Failed to deserialize content from laydown.ron: missing field `history`', /home/x667421/.cargo/registry/src/github.com-1ecc6299db9ec823/laydown-1.5.0/src/data_file.rs:52:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

All this command (and maybe others, I can't access help...) shouldn't break when `laydown.ron` is not possible to deserialize. I mean they should not attempt to deserialize it.

**Comment by badjr13** [comment]
Thank you for creating this issue. I will look into fixing this when I have an opportunity.

**Comment by loginn** [comment]
As a note, this happens when updating from a version that didnt have the `undo` command.
I'll make a fix today, but I think just adding the history field to `laydown.ron` should be the preferred method.

**Comment by badjr13** [comment]
Hey, thank you for following back on this. I apologize I haven't addressed this yet. I've been spending my free time on another project. If you make any updates, I'd be happy to review and merge them sooner than later.

**Comment by Zykino** [comment]
You kind of fixed #22 instead of this issue, by doing an upgrade.

I would have "early quit" when it is not needed to de-serialize `laydown.ron` for this issue. Since we can `laydown edit`, we can break the file. Breaking the file need mean that  `laydown [edit|config-dir|clear|archive|help]` (or even `version` some day?) would not be possible. So it can be harder to fix or report the issue.

Looking briefly at the code, I think that [deserialisation](https://github.com/badjr13/laydown/blob/65a01aeaed76713407e18c97cf339ae7a71a91ad/src/lib.rs#L33-L34) should be moved only where necessary. Maybe keep open the file all the time, if you must, but parse it as a `standup` only when necessary?

**Comment by badjr13** [comment]
> deserialisation should be moved only where necessary

is a good idea; ideally, we get the application to that state. However, this application isn't my priority at the moment as I focus on other projects. I believe https://github.com/badjr13/laydown/issues/22 addresses the major bug. I will keep this issue open and get around to it when I can. If you were to open a PR with the code in place, I would be happy to prioritize reviewing it.

**Comment by loginn** [comment]
Oh that makes sense. I can make that fix too. I only work half of the day today :>
