### ISSUE TITLE
Maybe `vi` is not the best default editor?

### ISSUE THREAD

**Issue by Zykino** [badjr13/laydown#24]
I see that the [default editor is configured](https://github.com/badjr13/laydown/blob/e6daf3498cad940c72592d93485ff04050fab061/src/lib.rs#L44) to be `vi`.
I like to use `vim` and `kakoune`, but they are not easy or even intuitive editors. If someone did not configure it's `EDITOR` env variable I think that `nano` is much more easy to use (not as easy to move lines from DO to DID) and is also installed everywhere.

It does not affect me, but any new linux/BSD user. Not sure how it will work on windows 🤔 (if laydown work there).

**Comment by badjr13** [comment]
I wouldn't say that `vi` is the default. `vi` is in the codebase as a last resort. If the user has their `$EDITOR` environment variable set or if they pass the name of an editor as an argument with the `edit` command, they can use the editor of their choice. Given that this app is a terminal-based application, I'm comfortable making the assumption that any user who installs and uses this application is capable of navigating around this and using their editor of choice,

**Comment by Zykino** [comment]
I agree, but if I put myself in the shoes of a linux beginner I don't know how to set `$EDITOR`, see that I can edit the file and will be blocked there not even knowing I am in `vi`. So no way to even look for the SO issue to exit `vim`. Sure I read to fast the help, or I did it right the first time and forgot the second time (or mis-configured `$EDITOR`). `nano` as a last resort can tell me how to exit it and I can fix a typo without having pre-required knowledge of my editor.

**Comment by Zykino** [comment]
I just discovered `editor` that is a symlink managed with `sudo update-alternatives --config editor`. I don’t know if it is used on every linux distro but apparently `sudoedit` is using this.
