### ISSUE TITLE
Ability to move an item from "doing" to "did"

### ISSUE THREAD

**Issue by ctaschereau** [badjr13/laydown#7]
If I start a task (and I log it as "doing" in laydown) and complete it during the day, I would like to be able to move it from "doing" to "did".

If I find time, I might try to come up with a pull request.

**Comment by badjr13** [comment]
Though there currently isn't a command for this exact action, it could be done via the `edit` command pretty easily.

**Comment by badjr13** [comment]
I didn't mean to close this issue when I added my last comment.
